ROUGHNESS_LOW = 'roughness_low'
ROUGHNESS_MID = 'roughness_mid'
ROUGHNESS_HIGH = 'roughness_high'
ROUGHNESS = (ROUGHNESS_LOW, ROUGHNESS_MID, ROUGHNESS_HIGH)

TEMPERATURE_LOW = 'temperature_low'
TEMPERATURE_MID = 'temperature_mid'
TEMPERATURE_HIGH = 'temperature_high'
TEMPERATURE = (TEMPERATURE_LOW, TEMPERATURE_MID, TEMPERATURE_HIGH)

ACQUATIC_NONE = 'acquatic_none'
ACQUATIC_COASTAL = 'acquatic_coastal'
ACQUATIC_SMALL_BODY = 'acquatic_small_body'
ACQUATIC_LARGE_BODY = 'acquatic_large_body'

ACQUATIC = (ACQUATIC_NONE, ACQUATIC_COASTAL, ACQUATIC_SMALL_BODY, ACQUATIC_LARGE_BODY)

BARREN = 'barren'
WOODED = 'wooded'

WOOD = (BARREN, WOODED)