class MinecraftColor:
    white = "white"
    light_gray = "light_gray"
    gray = "gray"
    black = "black"
    brown = "brown"
    red = "red"
    orange = "orange"
    yellow = "yellow"
    lime = "lime"
    green = "green"
    cyan = "cyan"
    light_blue = "light_blue"
    blue = "blue"
    purple = "purple"
    magenta = "magenta"
    pink = "pink"
